<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_npru</name>
   <tag></tag>
   <elementGuidId>a5456913-8ed2-47bc-842d-56746917c101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b._yb_7oly8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='ybar-sf']/div/div/div/ul/li/span/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>84a30f17-caba-4df9-9a4a-84d35a2c1b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_yb_7oly8</value>
      <webElementGuid>553109bf-c6b6-4b32-b192-7dad71c58c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>npru</value>
      <webElementGuid>5e378da7-5737-4bda-8d69-10b6c82c7369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ybar-sf&quot;)/div[@class=&quot;_yb_w6xyq&quot;]/div[@class=&quot;_yb_1igqf _yb_1r4bd&quot;]/div[@class=&quot;_yb_1nfum&quot;]/ul[@class=&quot;_yb_1ws6q&quot;]/li[@class=&quot;_yb_xe8nk _yb_1jdye _yb_1fy5d&quot;]/span[@class=&quot;_yb_xr24s&quot;]/b[@class=&quot;_yb_7oly8&quot;]</value>
      <webElementGuid>bb17b23d-30d1-466d-9ef0-87087199730b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ybar-sf']/div/div/div/ul/li/span/b</value>
      <webElementGuid>803e96ac-a3c6-422f-8323-7ec803069c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>910d85b4-7c8c-49d3-b2f0-baf157d6ecd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'npru' or . = 'npru')]</value>
      <webElementGuid>7f2b831a-3f2c-443f-9e50-6825ed142998</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
