<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_All Videos Images News Local Shopping M_cc1a71</name>
   <tag></tag>
   <elementGuidId>ba4766a3-e784-475f-a5ff-3eb6d30aac2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#horizontal-bar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='horizontal-bar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc4acf87-0398-4167-b269-5dbdc3a7f3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>horizontal-bar</value>
      <webElementGuid>6b63cb4d-25ab-472c-86a9-024a971e4075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aa5</name>
      <type>Main</type>
      <value>65a62ea43ea31</value>
      <webElementGuid>28c86091-19ad-42d0-b37a-910837b60cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ys-grid ys-hmenu</value>
      <webElementGuid>0042b25e-6604-417d-bc74-975e172d6220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Videos Images News Local Shopping MoreAnytime Past day Past week Past month AnytimeGet beautiful photos on every new browser tab. Download >></value>
      <webElementGuid>c80b8fe4-7327-4405-ae59-affb77980954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;horizontal-bar&quot;)</value>
      <webElementGuid>98813d39-99c6-4ef4-b5c0-e3b07829051e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='horizontal-bar']</value>
      <webElementGuid>30d8e7cc-c875-4e30-b9d0-a3085f57f461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ys']/div</value>
      <webElementGuid>5a5b1e11-8fc1-4630-9506-cb728c5455de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>6a5e4558-5bbf-413f-9644-b97334c1b614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'horizontal-bar' and (text() = 'All Videos Images News Local Shopping MoreAnytime Past day Past week Past month AnytimeGet beautiful photos on every new browser tab. Download >>' or . = 'All Videos Images News Local Shopping MoreAnytime Past day Past week Past month AnytimeGet beautiful photos on every new browser tab. Download >>')]</value>
      <webElementGuid>1f1555db-a18c-4cb4-8373-5ba05a8ea5bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
